services:
  whattime-bot:
    build: .              # This tells Docker to build from Dockerfile in current directory
    container_name: whattime-bot
    restart: unless-stopped
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_APPLICATION_ID=${DISCORD_APPLICATION_ID}
    volumes:
      - bot-data:/app/data

volumes:
  bot-data:
    name: whattime-bot-data
